### ISSUE TITLE
Running On My system

### ISSUE THREAD

**Issue by xelese** [mimre25/isosurface-analysis#1]
Hey! I have been interested in this project for a while and therefore was trying to run this on my laptop. I have been trying to run it but for some reason I am not able to execute it. 
I have all the required libraries installed.
When I try to run single.json the following error keeps occurring.

![a](https://user-images.githubusercontent.com/33120384/45475768-e9aa6c80-b75a-11e8-9157-425848659a31.png)

Any help with installation or execution on my part deeply appreciated.

**Comment by mimre25** [comment]
Hey!
Can you double check that you have the file you're trying to analyze? 
So in your case, does the file ionization/GT/GT0150.dat exist?

It works completely fine on my machine with a fresh checkout and build.

**Comment by xelese** [comment]
Hey thank you for responding! No the file doesn't exist in the archives, that actually might be the problem. Is it possible to update GitHub with the files? I'd be really glad if you did.

**Comment by xelese** [comment]
I'm still trying to run this... possibly there might be an error on my end can you please at least give me a procedure on how you installed the files for execution.
I have done **cmake** and **make all** for the files in the directory.. followed by the same thing in isosurface library. Can you guide me to the right path if I am mistaken.

**Comment by mimre25** [comment]
I think you've installed everything correctly.

You just need some data sets as input. I will see if the ones I used as example in the config files are publicly available.

May I ask you what data are you planning to analyze?

**Comment by xelese** [comment]
Oh! Hey thanks for responding, I did go through the IEEE paper and was interested in the ionization data set, although climate data set would be good too if you can make it available.

**Comment by mimre25** [comment]
The data sets are publicly available:

hurricane
http://vis.computer.org/vis2004contest/data.html

ionization
http://sciviscontest.ieeevis.org/2008/data.html

May I ask what are you trying to do with them?

**Comment by xelese** [comment]
Thanks! I am a student at undergraduate level looking into this project strictly for educational and personal purposes only. I have no intention of tampering with the project or to pass it as my own. This project seemed interesting to me so, I have been trying to implement it on  my system. Thanks for all the help!

**Comment by mimre25** [comment]
Oh that's cool. 
Could you please shoot me an email to mimre@nd.edu to follow up on this and for further discussions?
Thanks.

~ I'll close this issue now as it seems to be resolved
